try:
    f = open('no_name')
except Exception as e:
    print('error')
    print(e)